#!/usr/bin/env bash
# Launch Qwen3-VL-8B GRPO+OPSD on RRSIS-D, initialized from an existing SFT
# checkpoint. This stage-only wrapper intentionally does not rerun SFT.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../../.." && pwd)"
cd "$repo_root"

timestamp="${RUN_TIMESTAMP:-$(date +%Y%m%d-%H%M%S)}"
sft_ckpt="${SFT_CKPT:-/mnt/jfs/copilot/lhb/checkpoint/rs/rs-sft/gui-sd-qwen3-8b-rrsisd_sft_e1_retry-20260529-094035/v0-20260529-094457/checkpoint-96}"

export EXPERIMENT_SLUG="${EXPERIMENT_SLUG:-q8b-sft96-grpo-opsd-metric-gaussian}"
export RUN_NAME="${RUN_NAME:-gui-sd-qwen3-8b-rrsisd_sft96_grpo_opsd_metric_gaussian_e1-${timestamp}}"
export RJOB_NAME="${RJOB_NAME:-q8b-sft96-grpo-opsd-gauss-e1-${timestamp}}"
export RJOB_LOG_PATH="${RJOB_LOG_PATH:-/data/codes/gui_grounding/data/logs/training/${RJOB_NAME}.rjob.log}"
export WORKER_SCRIPT="${WORKER_SCRIPT:-${repo_root}/tools/training/run_qwen3_4b_base_rsfull_grpo_sdpo_2node_worker.sh}"

export RJOB_GROUP="${RJOB_GROUP:-gui_agent}"
export RJOB_CHARGED_GROUP="${RJOB_CHARGED_GROUP:-gui_agent}"
export RJOB_CPU="${RJOB_CPU:-64}"
export RJOB_GPU="${RJOB_GPU:-8}"
export RJOB_MEMORY="${RJOB_MEMORY:-800000}"
export RJOB_REPLICA="${RJOB_REPLICA:-2}"
export RJOB_REPLICA_RESTART="${RJOB_REPLICA_RESTART:-never}"
export RJOB_BACKOFF_LIMIT="${RJOB_BACKOFF_LIMIT:-1}"
export RJOB_MAX_WAIT_DURATION="${RJOB_MAX_WAIT_DURATION:-16h0m0s}"
export RJOB_POSITIVE_TAGS="${RJOB_POSITIVE_TAGS:-feature/gpfs=yes}"
export RJOB_PREFER_NEW_MACHINE="${RJOB_PREFER_NEW_MACHINE:-true}"

# Keep the local brainctl follower from holding the tmux pane after both
# replicas print the worker completion line.
export COMPLETION_GREP_PATTERN="${COMPLETION_GREP_PATTERN:-\\[4b-2node-worker\\].*completed}"
export COMPLETION_GRACE_SEC="${COMPLETION_GRACE_SEC:-60}"

export BASE_MODEL_PATH="$sft_ckpt"
export MODEL_PATH="$sft_ckpt"
export TEACHER_PATH="$sft_ckpt"
export ROLLOUT_MODEL_PATH="$sft_ckpt"
export CKPT_ROOT="${CKPT_ROOT:-/mnt/jfs/copilot/lhb/checkpoint/rs/rs-sd}"
export ARTIFACT_ROOT="${ARTIFACT_ROOT:-/mnt/jfs/copilot/lhb/artifacts/rs/rs-sd}"
export TRAIN_JSONL="${TRAIN_JSONL:-/data/codes/gui_grounding/data/rs_full/rs_train.jsonl}"
export TEST_JSONL="${TEST_JSONL:-/data/codes/gui_grounding/data/rs_full/rs_test.jsonl}"

export NNODES="${NNODES:-2}"
export NPROC_PER_NODE="${NPROC_PER_NODE:-7}"
export TRAIN_CUDA_VISIBLE_DEVICES="${TRAIN_CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6}"
export ROLLOUT_CUDA_VISIBLE_DEVICES="${ROLLOUT_CUDA_VISIBLE_DEVICES:-7}"
export MASTER_PORT="${MASTER_PORT:-31330}"
export VLLM_SERVER_PORT="${VLLM_SERVER_PORT:-9142}"
export RENDEZVOUS_TIMEOUT_SEC="${RENDEZVOUS_TIMEOUT_SEC:-1200}"
export ROLLOUT_READY_TIMEOUT_SEC="${ROLLOUT_READY_TIMEOUT_SEC:-1200}"

export NUM_TRAIN_EPOCHS="${NUM_TRAIN_EPOCHS:-1}"
export MAX_STEPS="${MAX_STEPS:--1}"
export SAVE_STEPS="${SAVE_STEPS:-10}"
export SAVE_TOTAL_LIMIT="${SAVE_TOTAL_LIMIT:-20}"
export SAVE_ONLY_MODEL="${SAVE_ONLY_MODEL:-true}"
export TUNER_TYPE="${TUNER_TYPE:-full}"
export ALLOW_RESUME="${ALLOW_RESUME:-false}"
export AUTO_RESUME="${AUTO_RESUME:-false}"

export PER_DEVICE_TRAIN_BATCH_SIZE="${PER_DEVICE_TRAIN_BATCH_SIZE:-2}"
export GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-4}"
export LR="${LR:-8e-7}"
export WARMUP_RATIO="${WARMUP_RATIO:-0.01}"
export NUM_GENERATIONS="${NUM_GENERATIONS:-8}"
export NUM_ITERATIONS="${NUM_ITERATIONS:-1}"
export MAX_LENGTH="${MAX_LENGTH:-20000}"
export MAX_COMPLETION_LENGTH="${MAX_COMPLETION_LENGTH:-64}"
export DEEPSPEED_CONFIG="${DEEPSPEED_CONFIG:-zero2}"
export TEACHER_DEEPSPEED_CONFIG="${TEACHER_DEEPSPEED_CONFIG:-zero3}"
export OFFLOAD_TEACHER_MODEL="${OFFLOAD_TEACHER_MODEL:-false}"

export VLLM_GPU_MEMORY_UTIL="${VLLM_GPU_MEMORY_UTIL:-0.78}"
export VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-20000}"
export DATASET_NUM_PROC="${DATASET_NUM_PROC:-8}"
export DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-8}"

export SDPO_LAMBDA="${SDPO_LAMBDA:-0.25}"
export SDPO_TAU_GOOD="${SDPO_TAU_GOOD:-0.5}"
export SDPO_TAU_FAIL="${SDPO_TAU_FAIL:-0.3}"
export SDPO_DELTA="${SDPO_DELTA:-0.5}"
export SDPO_GRPO_FAILED_WEIGHT="${SDPO_GRPO_FAILED_WEIGHT:-1.0}"
export SDPO_DISTILL_SCOPE="${SDPO_DISTILL_SCOPE:-failed}"
export SDPO_TARGET="${SDPO_TARGET:-rollout}"
export SDPO_HINT_SOURCE="${SDPO_HINT_SOURCE:-gt}"
export SDPO_TEACHER_REFRESH_MODE="${SDPO_TEACHER_REFRESH_MODE:-metric}"
export SDPO_TEACHER_REFRESH_STEP="${SDPO_TEACHER_REFRESH_STEP:--1}"
export SDPO_TEACHER_REFRESH_WARMUP="${SDPO_TEACHER_REFRESH_WARMUP:-80}"
export SDPO_TEACHER_REFRESH_WINDOW="${SDPO_TEACHER_REFRESH_WINDOW:-50}"
export SDPO_TEACHER_REFRESH_CHECK_INTERVAL="${SDPO_TEACHER_REFRESH_CHECK_INTERVAL:-10}"
export SDPO_TEACHER_REFRESH_MAX_REFRESHES="${SDPO_TEACHER_REFRESH_MAX_REFRESHES:-1}"
export SDPO_TEACHER_REFRESH_COOLDOWN_STEPS="${SDPO_TEACHER_REFRESH_COOLDOWN_STEPS:-0}"

export OPSD_MASK_MODE="${OPSD_MASK_MODE:-gaussian}"
export OPSD_HINT_MODE="${OPSD_HINT_MODE:-hint}"
export OPSD_TOKEN_WEIGHT_MODE="${OPSD_TOKEN_WEIGHT_MODE:-uniform-entropy}"
export OPSD_NON_DIGIT_WEIGHT="${OPSD_NON_DIGIT_WEIGHT:-0.05}"
export OPSD_MAX_DIGIT_LEN="${OPSD_MAX_DIGIT_LEN:-3}"
export OPSD_EMA_DECAY="${OPSD_EMA_DECAY:-0.0}"
export OPSD_GAUSSIAN_SIGMA_RATIO="${OPSD_GAUSSIAN_SIGMA_RATIO:-1.5}"
export OPSD_JITTER_RATIO="${OPSD_JITTER_RATIO:-0.2}"

export GRPO_BETA="${GRPO_BETA:-0.04}"
export ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-0.7}"
export TOP_P="${TOP_P:-0.95}"
export TOP_K="${TOP_K:-50}"
export SKIP_EVAL="${SKIP_EVAL:-true}"
export STAGE2_SKIP_EVAL="${STAGE2_SKIP_EVAL:-true}"

mkdir -p /data/codes/gui_grounding/data/logs/training

echo "[q8b-sft-ckpt-grpo-opsd] timestamp=${timestamp}"
echo "[q8b-sft-ckpt-grpo-opsd] sft_ckpt=${sft_ckpt}"
echo "[q8b-sft-ckpt-grpo-opsd] run_name=${RUN_NAME}"
echo "[q8b-sft-ckpt-grpo-opsd] rjob_name=${RJOB_NAME}"
echo "[q8b-sft-ckpt-grpo-opsd] log_path=${RJOB_LOG_PATH}"
echo "[q8b-sft-ckpt-grpo-opsd] output=${CKPT_ROOT}/${RUN_NAME}"

bash "${repo_root}/tools/training/launch_qwen3_4b_rsfull_grpo_sdpo_2node_experiment_rjob.sh"
